---
ospf:
  id: "99"
  rid: "11.11.11.11"
  default_originate: false 
  networks:
    - network: "11.11.0.0"
      wildcard: "0.0.255.255"
      area: "0"
    - network: "11.11.11.11"
      wildcard: "0.0.0.0"
      area: "0"


BGP:
  ASN: "65011"
  peers:
    - neighbor: "10.10.0.6"
      peer_asn: "65010"
  networks:
    - network: "10.10.10.10"
      mask: "255.255.255.255"

  