---
BGP:
  ASN: "65009"
  peers:
    - neighbor: "10.10.0.0"
      peer_asn: "65008"

    - neighbor: "10.10.0.5"
      peer_asn: "65010"

eigrp_style: "named"

eigrp: 
  asn: "9"
  name: "R9"

ospf:
  id: "99"
  rid: "9.9.9.9"
  default_originate: true
  networks:
    - network: "9.9.0.0"
      wildcard: "0.0.255.255"
      area: "0"
    - network: "9.9.9.9"
      wildcard: "0.0.0.0"
      area: "0"
