---
BGP:
  ASN: "65010"
  peers:
    - neighbor: "10.10.0.2"
      peer_asn: "65008"

    - neighbor: "10.10.0.4"
      peer_asn: "65009"
  networks:
    - network: "10.10.10.10"
      mask: "255.255.255.255"

ospf:
  id: "99"
  rid: "10.10.10.10"
  default_originate: false 
  networks:
    - network: "10.10.0.0"
      wildcard: "0.0.255.255"
      area: "0"
    - network: "10.10.10.10"
      wildcard: "0.0.0.0"
      area: "0"
