---
ntp: 
   severs:
   - "1.1.1.1"
   - "2.2.2.2"
   - "3.3.3.3"
   - "4.4.4.4"
   - "5.5.5.5"
   - "6.6.6.6"
BGP:
  ASN: "65008"
  peers:
    - neighbor: "10.10.0.1"
      peer_asn: "65009"

    - neighbor: "10.10.0.3"
    
      peer_asn: "65010"

eigrp_style: "normal"

eigrp: 
  asn: "8"
  rid: "8.8.8.8"
  networks:
    - "10.0.0.0 0.255.255.255"
    - "192.168.86.0 0.0.0.255"
    - "8.8.8.8 0.0.0.0"
