ospf_configure:
  Cisco-IOS-XE-native:router:
    Cisco-IOS-XE-ospf:router-ospf:
      ospf:
        process-id:
        - id: 1
          network:
          - area: 0
            ip: 0.0.0.0
            wildcard: 255.255.255.255
          router-id: 17.17.17.17

acl_configure:
  Cisco-IOS-XE-native:access-list:
    Cisco-IOS-XE-acl:extended:
    - access-list-seq-rule:
      - ace-rule:
          action: deny
          dscp: ef
          dst-any:
          -
          host: 6.7.1.2
          protocol: ip
        sequence: '55'
      name: hsaljuboori
    - name: meraki-fqdn-dns
