---
- name: "My Banner Playbook"
  hosts: qa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "configure MOTD"
      cisco.ios.ios_banner:
        banner: motd
        text: |
          this is my banner for all of my network devices
        state: present
      register: my_banner
      
    - debug: var=my_banner

