---
- name: "Print some encrypted stuff"
  hosts: qa 
  gather_facts: false
  connection: network_cli


  tasks:
    - name: "Task-1- decrypt and prtint"
      debug:
        msg: "{{ ntp }}"
    - name: "Task2- decypt and print1"
      debug:
        msg: "{{ bgp }}"