---
- name: "Filter Test"
  hosts: "192.168.86.23"


  tasks:
  - name: "Testing some filter"
    vars:
      qa_prefixes:
         - "192.168.1.0/24"
         - "10.0.0.0/8"
         - "172.16.1.0/24"
    
      prod_prefixes:
        - "192.168.2.0/24"
        - "10.0.0.0/8"
        - "172.16.2.0/24"
    debug:
         # msg: "{{ qa_prefixes | symmetric_difference(prod_prefixes) }}"
            msg: "{{ qa_prefixes | to_nice_yaml}}"