---

- name: "Loop test"
  hosts: qa
  gather_facts: true
  connection: network_cli


  tasks:
  - name: " loop through IP info"
    debug:
      msg: "{{ ansible_facts ['net_hostname']  }} has an IP addres {{ item }} configured "
    loop: "{{ ansible_facts['net_all_ipv4_address'] }}"