---
- name: "REGISTER PLAYBOOK"
  hosts: 192.168.86.23
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "configure MOTD"
      cisco.ios.ios_config:
           src: "ntp.j2"
      register: ntp_result
    -  name: "Print results"
       debug:
         msg: "{{ ntp_result }}"
