---


- name: "PLAYBOOK EIGRP STUFF"
  hosts: 192.168.86.23
  connection: network_cli

  tasks:


    - name: "Task 1- Psuh EIGRP config"
      cisco.ios.ios_config:
        src: "eigrp1.j2"
      register: "eigrp_result" 

    -  name: "Task 2 - print EIGRP config"
       debug:
         msg: "{{ eigrp_result.commands }}"

    - name: "Task 3 - verfiy EIGRP config"
      cisco.ios.ios_command:
        commands:
          - "show run | section eigrp"
          - "show ip arp"
      register: "eigrp_show_output"

    - name: "Task 4 - print veify commands"
      debug:
        msg: "{{ eigrp_show_output.stdout_lines }}"
