---
- name: "PLAYBOOK EIGRP STUFF"
  hosts: 192.168.86.23
  connection: network_cli
  
  roles:
    - eigrp-role
  
  tasks:
    - name: "FUTHER VEIFICATION"
      cisco.ios.ios_command:
        commands:
          - "show ip eigrp interface"
      register: "show_further_verification"

    - name: " PRINT VERIFICATION"
      debug:
         msg: "{{ show_further_verification.stdout_lines }}" 

