---
- name: "PLAYBOOK EIGRP STUFF"
  hosts: 192.168.86.23
  connection: network_cli

  tasks:


    - name: "Task 1 - Send a show command"
      cisco.ios.ios_command:
        commands: "show version"
      register: "show_version_output"

    - name: " Task 2 - Parse show command"
      set_fact:
        pasered_data: >-
          {{ show_version_output.stdout_lines[0]  | clay584.genie.parse_genine(
          command= 'show version', os='ios ') }}

    - name: "Task 3 - print output"
      debug:
        msg: "{{ pasered_data }}"
