---

- name: "Loop test"
  hosts: qa
  gather_facts: true
  connection: network_cli


  tasks:
  - name: " loop through IP info"
    debug:
      msg: "{{ ansible_facts ['net_hostname'] }}  running version  {{ ansible_facts ['net_version'] }}"