---
- name: "OSPF Playbook"
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push Cisco OSPF Config"
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 2
              router_id: "{{ ospf.rid }}"
              network:
                - address:  0.0.0.0
                  wildcard_bits: 255.255.255.255 
                  area: 0
        state: merged
      register : cisco_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Print Cisco OSPF Config"
      debug:
        msg: " {{ cisco_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"
