---
- name: "OSPF Playbook"
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push Cisco OSPF Config"
      cisco.ios.ios_config:
        src: "{{ ansible_network_os }}-ospf.j2"
      register : cisco_output
      when: "ansible_network_os == 'cisco.ios.ios'"

    - name: "Print Cisco OSPF Config"
      debug:
        msg: " {{ cisco_output }}"
      when: "ansible_network_os == 'cisco.ios.ios'"
