---
  name: MY FIRST PLAYBOOK
  hosts: all
  gather_facts: false 
  connection: network_cli

  tasks:
         name: OSPF_CONFIG
         cisco.ios.ios_config:
          lines:
           - router-id 88.88.88.88
          parents:
            - router ospf 11 
          register: my_output


         debug: var=my_output 
