---

- name: "Configure Device via RESTCONF"
  hosts: crs
  connection: local
  tasks:
    - name: "Task 2 - Configure ACL"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/native/ip/access-list"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: PUT 
        headers:
          Accept:
            application/yang-data+json,
            application/yang-data.errors+json
          Content-Type: 'application/yang-data+json'
        body_format: json 
        body: "{{ acl_configure }}"
        validate_certs: false
        status_code:
          - 200
          - 204
      register: result_task1
    
          
    - name: "Task 2- Print Result"
      debug:
        msg: "{{ result_task1 }}"

