---
- name: "Play 1- Target Cisco Devies"
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Push Cisco Syslog Config"
      cisco.ios.ios_logging_global:
        config:
          hosts:
            - hostname: "{{ item.ip }}"
        state: merged
      loop: "{{ syslog.hosts }}"
      when: item.port is not defined 
      register : task1_output


    - name: "Push Cisco Syslog Config"
      cisco.ios.ios_logging_global:
        config:
           hosts:
             - hostname: "{{ item.ip }}"
               transport:
                 tcp:
                   port: "{{ item.port }}"
        state: merged
      loop: "{{ syslog.hosts }}"
      when: item.port is defined 
      register : task2_output

    - name: "Print Task-1"
      debug:
        msg: " {{ item }}"
      loop: "{{ task1_output.results }}"
      loop_control:
         label:  None
      when: item.commands is defined

    - name: "Print Task-2"
      debug:
        msg: " {{ item }}"
      loop: "{{ task2_output.results }}"
      loop_control:
        label: False
      when: item.commands is defined
